-- PIMCO Municipal Bond Demo - Dynamic Tables
-- Transformations from Bronze → Silver → Gold

-- Bronze to Silver: Clean and Standardize Transactions
CREATE OR REPLACE DYNAMIC TABLE SLV_009.DT_TXN_7821
TARGET_LAG = '1 minute'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    TX_ID as TX_ID,
    TD_DATE as TRADE_DATE,
    STL_DATE as SETTLEMENT_DATE,
    PRN_AMT as PRINCIPAL_AMOUNT,
    ISS_ID as ISSUER_ID,
    BND_ID as BOND_ID,
    TRD_TYPE as TRADE_TYPE,
    CUSIP as CUSIP,
    CURRENT_TIMESTAMP() as CREATED_TS
FROM BRZ_001.TX_0421
WHERE TD_DATE IS NOT NULL
  AND PRN_AMT IS NOT NULL
  AND BND_ID IS NOT NULL;

-- Bronze to Silver: Clean and Standardize Bond Dimension
CREATE OR REPLACE DYNAMIC TABLE SLV_009.DT_DIM_BND_001
TARGET_LAG = '1 minute'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    r.BND_ID as BND_ID,
    r.CUSIP as CUSIP,
    r.ISIN as ISIN,
    r.MAT_DATE as MATURITY_DATE,
    r.CPN_RATE as COUPON_RATE,
    r.CR_RT as CREDIT_RATING,
    r.ISS_TYPE as ISSUER_TYPE,
    CASE 
        WHEN r.ISS_TYPE LIKE '%TAX%EXEMPT%' OR r.ISS_TYPE LIKE '%MUNICIPAL%' THEN 'TAX_EXEMPT'
        WHEN r.ISS_TYPE LIKE '%TAXABLE%' THEN 'TAXABLE'
        ELSE 'OTHER'
    END as SEGMENT_CD,
    i.ISS_ID as ISSUER_ID,
    CURRENT_TIMESTAMP() as CREATED_TS,
    CURRENT_TIMESTAMP() as UPDATED_TS
FROM BRZ_001.REF_7832 r
LEFT JOIN BRZ_001.ISS_5510 i ON r.ISS_TYPE = i.ISS_TYPE
WHERE r.BND_ID IS NOT NULL;

-- Bronze to Silver: Clean and Standardize Issuer Dimension
CREATE OR REPLACE DYNAMIC TABLE SLV_009.DT_DIM_ISS_002
TARGET_LAG = '1 minute'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    ISS_ID as ISS_ID,
    ISS_NAME as ISSUER_NAME,
    ISS_TYPE as ISSUER_TYPE,
    STATE_CD as STATE_CODE,
    MUN_NAME as MUNICIPALITY_NAME,
    CASE 
        WHEN STATE_CD IN ('CA', 'NY', 'TX', 'FL', 'IL') THEN 'WEST'
        WHEN STATE_CD IN ('NY', 'NJ', 'CT', 'MA', 'PA') THEN 'NORTHEAST'
        WHEN STATE_CD IN ('TX', 'FL', 'GA', 'NC', 'VA') THEN 'SOUTH'
        WHEN STATE_CD IN ('IL', 'MI', 'OH', 'WI', 'MN') THEN 'MIDWEST'
        ELSE 'OTHER'
    END as REGION_CD,
    CURRENT_TIMESTAMP() as CREATED_TS,
    CURRENT_TIMESTAMP() as UPDATED_TS
FROM BRZ_001.ISS_5510
WHERE ISS_ID IS NOT NULL;

-- Bronze to Silver: Create Region Dimension
CREATE OR REPLACE DYNAMIC TABLE SLV_009.DT_DIM_REG_003
TARGET_LAG = '1 minute'
WAREHOUSE = 'MSJDEMO'
AS
SELECT DISTINCT
    REGION_CD as REGION_CD,
    CASE 
        WHEN REGION_CD = 'WEST' THEN 'Western Region'
        WHEN REGION_CD = 'NORTHEAST' THEN 'Northeast Region'
        WHEN REGION_CD = 'SOUTH' THEN 'Southern Region'
        WHEN REGION_CD = 'MIDWEST' THEN 'Midwest Region'
        ELSE 'Other Region'
    END as REGION_NAME,
    NULL as STATE_CODE,
    'GEOGRAPHIC' as REGION_TYPE,
    CURRENT_TIMESTAMP() as CREATED_TS
FROM SLV_009.DT_DIM_ISS_002
WHERE REGION_CD IS NOT NULL;

-- Bronze to Silver: Create Segment Dimension
CREATE OR REPLACE DYNAMIC TABLE SLV_009.DT_DIM_SEG_4421
TARGET_LAG = '1 minute'
WAREHOUSE = 'MSJDEMO'
AS
SELECT DISTINCT
    SEGMENT_CD as SEGMENT_CD,
    CASE 
        WHEN SEGMENT_CD = 'TAX_EXEMPT' THEN 'Tax-Exempt Municipal Bonds'
        WHEN SEGMENT_CD = 'TAXABLE' THEN 'Taxable Municipal Bonds'
        ELSE 'Other Bonds'
    END as SEGMENT_NAME,
    SEGMENT_CD as SEG_TYPE,
    CASE WHEN SEGMENT_CD = 'TAX_EXEMPT' THEN 1 ELSE 0 END as TAX_EXEMPT_FLAG,
    CURRENT_TIMESTAMP() as CREATED_TS
FROM SLV_009.DT_DIM_BND_001
WHERE SEGMENT_CD IS NOT NULL;

-- Silver to Gold: Aggregate Positions by Bond, Issuer, Region, Segment
CREATE OR REPLACE DYNAMIC TABLE GLD_003.DT_POS_9912
TARGET_LAG = '5 minutes'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    CONCAT('POS_', b.BND_ID, '_', CURRENT_DATE()) as POS_ID,
    b.BND_ID as BOND_ID,
    b.ISSUER_ID as ISSUER_ID,
    i.REGION_CD as REGION_CD,
    b.SEGMENT_CD as SEGMENT_CD,
    COALESCE(SUM(t.PRINCIPAL_AMOUNT), 0) as PAR_VALUE,
    COALESCE(SUM(t.PRINCIPAL_AMOUNT * (1 + b.COUPON_RATE / 100)), 0) as MARKET_VALUE,
    CURRENT_DATE() as POSITION_DATE,
    CURRENT_DATE() as AS_OF_DATE,
    CURRENT_TIMESTAMP() as CREATED_TS
FROM SLV_009.DT_DIM_BND_001 b
LEFT JOIN SLV_009.DT_TXN_7821 t ON b.BND_ID = t.BOND_ID
LEFT JOIN SLV_009.DT_DIM_ISS_002 i ON b.ISSUER_ID = i.ISS_ID
WHERE t.TRADE_DATE >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY b.BND_ID, b.ISSUER_ID, i.REGION_CD, b.SEGMENT_CD;

-- Silver to Gold: Segment Aggregations
CREATE OR REPLACE DYNAMIC TABLE GLD_003.DT_SEG_4421
TARGET_LAG = '5 minutes'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    SEGMENT_CD,
    CURRENT_DATE() as AS_OF_DATE,
    SUM(PAR_VALUE) as TOTAL_PAR_VALUE,
    SUM(MARKET_VALUE) as TOTAL_MARKET_VALUE,
    COUNT(DISTINCT BOND_ID) as POSITION_COUNT
FROM GLD_003.DT_POS_9912
GROUP BY SEGMENT_CD;

-- Silver to Gold: Region Aggregations
CREATE OR REPLACE DYNAMIC TABLE GLD_003.DT_REG_7733
TARGET_LAG = '5 minutes'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    REGION_CD,
    CURRENT_DATE() as AS_OF_DATE,
    SUM(PAR_VALUE) as TOTAL_PAR_VALUE,
    SUM(MARKET_VALUE) as TOTAL_MARKET_VALUE,
    COUNT(DISTINCT BOND_ID) as POSITION_COUNT
FROM GLD_003.DT_POS_9912
WHERE REGION_CD IS NOT NULL
GROUP BY REGION_CD;

-- Silver to Gold: Issuer Aggregations
CREATE OR REPLACE DYNAMIC TABLE GLD_003.DT_ISS_8844
TARGET_LAG = '5 minutes'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    ISSUER_ID,
    CURRENT_DATE() as AS_OF_DATE,
    SUM(PAR_VALUE) as TOTAL_PAR_VALUE,
    SUM(MARKET_VALUE) as TOTAL_MARKET_VALUE,
    COUNT(DISTINCT BOND_ID) as POSITION_COUNT
FROM GLD_003.DT_POS_9912
WHERE ISSUER_ID IS NOT NULL
GROUP BY ISSUER_ID;

-- Silver to Gold: Growth Metrics Over Time
CREATE OR REPLACE DYNAMIC TABLE GLD_003.DT_GRO_5566
TARGET_LAG = '1 hour'
WAREHOUSE = 'MSJDEMO'
AS
SELECT 
    CURRENT_DATE() as METRIC_DATE,
    SEGMENT_CD,
    REGION_CD,
    SUM(PAR_VALUE) as TOTAL_PAR_VALUE,
    SUM(MARKET_VALUE) as TOTAL_MARKET_VALUE,
    SUM(PAR_VALUE) - LAG(SUM(PAR_VALUE)) OVER (
        PARTITION BY SEGMENT_CD, REGION_CD 
        ORDER BY CURRENT_DATE()
    ) as VALUE_CHANGE,
    CASE 
        WHEN LAG(SUM(PAR_VALUE)) OVER (
            PARTITION BY SEGMENT_CD, REGION_CD 
            ORDER BY CURRENT_DATE()
        ) > 0
        THEN ((SUM(PAR_VALUE) - LAG(SUM(PAR_VALUE)) OVER (
            PARTITION BY SEGMENT_CD, REGION_CD 
            ORDER BY CURRENT_DATE()
        )) / LAG(SUM(PAR_VALUE)) OVER (
            PARTITION BY SEGMENT_CD, REGION_CD 
            ORDER BY CURRENT_DATE()
        )) * 100
        ELSE 0
    END as PCT_CHANGE
FROM GLD_003.DT_POS_9912
WHERE REGION_CD IS NOT NULL AND SEGMENT_CD IS NOT NULL
GROUP BY SEGMENT_CD, REGION_CD;

