# DataHub Cloud PagerDuty Action Configuration
name: "datahub_pagerduty_action"
enabled: true

# DataHub Cloud connection configuration
datahub:
  server: "https://<namespace>.acryl.io/gms"
  token: "${DATAHUB_GMS_TOKEN}"

# Event source configuration for DataHub Cloud
source:
  type: "datahub-cloud"
  config:
    # Only listen for EntityChangeEvent_v1 events (DataHub Cloud supported)
    event_types: ["EntityChangeEvent_v1"]
    
    # Filter for specific categories of interest
    filter:
      event:
        category: ["TECHNICAL_SCHEMA", "DEPRECATION", "OWNER", "TAG", "DOMAIN", "LIFECYCLE", "RUN"]

# Action configuration
action:
  type: "pagerduty"
  config:
    # PagerDuty configuration
    routing_key: "${PAGERDUTY_ROUTING_KEY}"
    base_url: "https://<namespace>.acryl.io"
    
    # Severity mapping for different event categories
    severity_mapping:
      TECHNICAL_SCHEMA: "warning"    # Schema changes are warnings
      DEPRECATION: "warning"         # Deprecations are warnings
      OWNER: "info"                  # Ownership changes are info
      TAG: "info"                    # Tag changes are info
      DOMAIN: "info"                 # Domain changes are info
      LIFECYCLE: "warning"           # Lifecycle changes are warnings
      RUN: "critical"                # Assertion failures are critical
    
    # Auto-resolution configuration
    enable_auto_resolve: true
    auto_resolve_operations: ["REMOVE"]
    
    # Custom fields for incidents
    custom_fields:
      environment: "${ENVIRONMENT:-production}"
      team: "data-engineering"
      service: "datahub"
      runbook_url: "https://wiki.company.com/data-incident-response"
    
    # Retry configuration
    max_retries: 3
    retry_delay: 1

# Pipeline configuration
pipeline:
  failure_mode: "CONTINUE"  # Continue processing even if some events fail
  max_events_per_batch: 100
  polling_interval_seconds: 30
