-- File: snowflake/setup/02_finserv_asset_mgmt_setup.sql
-- Purpose: Set up the Financial Services Asset Management demo
-- This script executes the steps from the Snowflake Financial Services Asset Management quickstart

-- Use ACCOUNTADMIN for setup
USE ROLE ACCOUNTADMIN;

-- Set up the warehouse for the Financial Services demo
CREATE WAREHOUSE IF NOT EXISTS FINSERV_WH 
    WAREHOUSE_SIZE = 'MEDIUM' 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE 
    COMMENT = 'Warehouse for Financial Services Asset Management demo';

-- Use the FINSERV_DEMO database
USE DATABASE FINSERV_DEMO;

-- Create schemas for the Financial Services demo
CREATE SCHEMA IF NOT EXISTS MARKET_DATA;
CREATE SCHEMA IF NOT EXISTS TRADING;
CREATE SCHEMA IF NOT EXISTS RISK;
CREATE SCHEMA IF NOT EXISTS REPORTING;

-- Create schema for Data Marketplace data
CREATE SCHEMA IF NOT EXISTS EXTERNAL;

-- Create tables for the demo
-- Market data tables
USE SCHEMA MARKET_DATA;

CREATE TABLE IF NOT EXISTS STOCK_PRICES (
    SYMBOL STRING,
    TRADE_DATE DATE,
    OPEN_PRICE FLOAT,
    HIGH_PRICE FLOAT,
    LOW_PRICE FLOAT,
    CLOSE_PRICE FLOAT,
    VOLUME INTEGER,
    SOURCE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Trading tables
USE SCHEMA TRADING;

CREATE TABLE IF NOT EXISTS TRADERS (
    TRADER_ID INTEGER,
    TRADER_NAME STRING,
    DESK STRING,
    REGION STRING,
    STATUS STRING,
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TRADES (
    TRADE_ID STRING,
    TRADER_ID INTEGER,
    TRADE_DATE DATE,
    TRADE_TIMESTAMP TIMESTAMP_NTZ,
    SYMBOL STRING,
    QUANTITY INTEGER,
    PRICE FLOAT,
    BUY_SELL STRING,
    STATUS STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
